dataset:
  name: 'dtu'
  image_root_dir: data
  fov: 90
  rot: 45
  resolution: 512
  crop_size: 512
  seed: 0
train:
  lr: 0.0002
model:
  model_type: pano_generation
  guidance_scale: 9.
  model_id: ../input1/models--stabilityai--stable-diffusion-2-base
  single_image_ft: False
  diff_timestep: 50

    
